@set allusersprofile=c:\programdata
@set appdata=c:\users\amonra\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=apollo
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\fsharp\
@set homedrive=c:
@set homepath=\users\amonra
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set include=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\shared;c:\program files (x86)\windows kits\10\include\10.0.18362.0\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\cppwinrt
@set inspector_2019_dir=c:\program files (x86)\intelswtools\inspector 2019\
@set inspxe_lang=en
@set ivirootdir32=c:\program files (x86)\ivi foundation\ivi\
@set ivirootdir64=c:\program files\ivi foundation\ivi\
@set kal_license_manager_bin_path=c:\program files\common files\keysight\license manager 6\bin
@set kal_license_manager_config_path=c:\programdata\keysight\licensing\configuration
@set keyshot_external_license_folder=c:\program files\spaceclaim 2017.1\
@set kmp_duplicate_lib_ok=true
@set lib=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\amonra\appdata\local
@set logonserver=\\apollo
@set mkl_serial=yes
@set moz_plugin_path=c:\program files (x86)\foxit software\foxit reader\plugins\
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set niextccompilersupp=c:\program files (x86)\national instruments\shared\externalcompilersupport\c\
@set number_of_processors=8
@set onedrive=c:\users\amonra\onedrive
@set opencv_dir=d:\opencv-2.4.10
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\fsharp\;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\bin\hostx64\x64;c:\program files (x86)\microsoft sdks\windows\v7.1a\\bin\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\program files (x86)\common files\oracle\java\javapath;c:\programdata\oracle\java\javapath;c:\program files\dell\dw wlan card;c:\program files (x86)\cuminas\document express djvu plug-in\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\calibre2\;c:\program files (x86)\ntp\bin;c:\anaconda2;c:\anaconda2\scripts;c:\anaconda2\library\bin;c:\program files\microsoft dnx\dnvm\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files (x86)\winmerge;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files\cmake\bin;c:\windows\system32\openssh\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\kensington\trackballworks;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files (x86)\ivi foundation\visa\winnt\bin\;c:\program files\ivi foundation\visa\win64\bin\;c:\program files (x86)\ivi foundation\visa\winnt\bin;c:\program files (x86)\ivi foundation\visa\winnt\ktvisa;c:\program files (x86)\ivi foundation\visa\winnt\agvisa;c:\program files (x86)\national instruments\shared\labview cli;c:\program files\tortoisegit\bin;c:\program files\dotnet\;c:\program files\microsoft network monitor 3\;c:\program files\git\cmd;c:\users\amonra\appdata\local\microsoft\windowsapps;c:\users\amonra\appdata\local\githubdesktop\bin;c:\users\amonra\appdata\local\microsoft\windowsapps;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\dr. memory\bin\;c:\program files (x86)\common files\acronis\tibmounter64;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\ninja
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\amonra\appdata\local\microsoft\visualstudio\15.0_eb5d8bc9\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 60 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=3c03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules;c:\program files\microsoft message analyzer\powershell\
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvsbuildtools_installdir_vs2017=c:\program files (x86)\microsoft visual studio\2017\community
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\2.1.508\sdks
@set qtinstalldir=c:\qt\5.12.8\msvc2017_64
@set qtmsbuild=c:\users\amonra\appdata\local\qtmsbuild
@set randfile=c:\program files (x86)\ntp\etc\.rnd
@set sessionname=console
@set spaceclaim_license_file=27581@localhost
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\amonra\appdata\local\temp
@set tmp=c:\users\amonra\appdata\local\temp
@set ucrtversion=10.0.18362.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=apollo
@set userdomain_roamingprofile=apollo
@set username=amonra
@set userprofile=c:\users\amonra
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc\14.16.27012\
@set vctoolsversion=14.16.27023
@set visualstudiodir=d:\users\amonra\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=d:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vs140comntools=d:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\
@set vs2017installdir=c:\program files (x86)\microsoft visual studio\2017\community
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=15.9.14
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\
@set vslang=1033
@set vsskuedition=community
@set vxipnppath=c:\program files (x86)\ivi foundation\visa\
@set vxipnppath64=c:\program files\ivi foundation\visa\
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.18362.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.18362.0\
@set windowssdkversion=10.0.18362.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set wxwin=d:\wxwidgets-3.0.2
@set z_trace=on
@set z_tracefile=c:\temp\ztracefile.txt
@set z_traceto=file
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\bin\hostx64\x64;c:\program files (x86)\microsoft sdks\windows\v7.1a\\bin\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\program files (x86)\common files\oracle\java\javapath;c:\programdata\oracle\java\javapath;c:\program files\dell\dw wlan card;c:\program files (x86)\cuminas\document express djvu plug-in\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\calibre2\;c:\program files (x86)\ntp\bin;c:\anaconda2;c:\anaconda2\scripts;c:\anaconda2\library\bin;c:\program files\microsoft dnx\dnvm\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files (x86)\winmerge;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files\cmake\bin;c:\windows\system32\openssh\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\kensington\trackballworks;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files (x86)\ivi foundation\visa\winnt\bin\;c:\program files\ivi foundation\visa\win64\bin\;c:\program files (x86)\ivi foundation\visa\winnt\bin;c:\program files (x86)\ivi foundation\visa\winnt\ktvisa;c:\program files (x86)\ivi foundation\visa\winnt\agvisa;c:\program files (x86)\national instruments\shared\labview cli;c:\program files\tortoisegit\bin;c:\program files\dotnet\;c:\program files\microsoft network monitor 3\;c:\program files\git\cmd;c:\users\amonra\appdata\local\microsoft\windowsapps;c:\users\amonra\appdata\local\githubdesktop\bin;c:\users\amonra\appdata\local\microsoft\windowsapps;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\dr. memory\bin\;c:\program files (x86)\common files\acronis\tibmounter64

@call "cl.exe" @"D:\Users\amonra\Documents\GitHub\DSS\DeepSkyStacker\DeepSkyStacker.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1