//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DeepSkyStackerEN.rc
//
#define IDC_DELETE                      2
#define IDC_ADD                         3
#define IDC_LOAD                        4
#define IDD_RGB                         105
#define IDD_LUMINANCE                   106
#define IDI_APP                         106
#define IDI_APPFILELIST                 107
#define IDI_OPENFILE                    108
#define IDI_UNDO                        109
#define IDI_REDO                        110
#define IDD_SETTINGS                    112
#define IDI_SETTINGS                    113
#define IDD_SATURATION                  113
#define IDB_ASINH                       115
#define IDB_CUBEROOT                    116
#define IDB_LOG                         118
#define IDB_LOGLOG                      119
#define IDB_LOGSQRT                     120
#define IDB_SQRT                        121
#define IDD_REGISTERSETTINGS            122
#define IDD_CHECKABOVE                  124
#define IDD_RAWSETTINGS                 126
#define IDD_EXPLORERBAR                 128
#define IDB_HDRUP                       129
#define IDB_HDRDOWN                     131
#define IDD_SAVEPICTURE                 132
#define IDI_LIGHTFRAME                  133
#define IDI_DARKFRAME                   134
#define IDS_SHOWREGISTEREDSTARS         134
#define IDI_FLATFRAME                   135
#define IDS_HIDEREGISTEREDSTARS         135
#define IDI_OFFSETFRAME                 136
#define IDS_UNDOLASTSETTINGS            136
#define IDB_LINEAR                      136
#define IDS_REDOLASTSETTINGS            137
#define IDD_ABOUT                       137
#define IDS_MANAGESETTINGS              138
#define IDR_LISTCONTEXT                 138
#define IDD_STACKRECAP                  139
#define IDD_PROPERTIES                  140
#define IDD_STACKSETTINGS               142
#define IDD_STACKINGPARAMETERS          143
#define IDD_RESULTSETTINGS              144
#define IDB_NORMALMODE                  144
#define IDB_MOSAICMODE                  145
#define IDD_REGISTERSETTINGS_BASIC      145
#define IDD_REGISTERSETTINGS_ADVANCED   146
#define IDB_GAMMAON                     147
#define IDD_RAWSETTINGS_TAB             147
#define IDB_GAMMAOFF                    148
#define IDD_FITSSETTINGS_TAB            148
#define IDB_PATTERN_RGGB                149
#define IDD_ALIGNMENTSETTINGS           149
#define IDB_PATTERN_BGGR                150
#define IDB_PATTERN_GBRG                151
#define IDB_PATTERN_GRBG                152
#define IDB_PATTERN_CYGMCYMG            153
#define IDB_IMAGELIST_GRAYSCALE         155
#define IDB_IMAGELIST_CFA_CYMG          156
#define IDB_IMAGELIST_CFA_RGB           157
#define IDB_BITMAP4                     158
#define IDB_IMAGELIST_COLOR             158
//#define IDB_BITMAP1                     160
#define IDB_IMAGELIST_MASK              160
#define IDD_DROPFILES                   162
#define IDD_STACKINGINTERMEDIATE        163
#define IDD_STARMASK                    164
#define IDB_CUSTOMMODE                  165
#define IDD_STACKINGCOMET               165
#define IDB_STARSHAPE_TRUNCATEDCONE     166
#define IDB_STARSHAPE_BELL              167
#define IDB_STARSHAPE_CONE              168
#define IDB_STARSHAPE_CUBIC             169
#define IDB_STARSHAPE_QUADRIC           170
#define IDB_STARSHAPE_TRUNCATEDBELL     171
#define IDB_BUTTONBASE_UP               176
#define IDB_BUTTONBASE_DOWN             177
#define IDB_BUTTONBASE_HOT              178
#define IDB_BUTTONBASE_MASK             179
#define IDB_BUTTONSTAR_UP               180
#define IDB_BUTTONCOMET_DISABLED        181
#define IDB_BUTTONCOMET_DOWN            182
#define IDB_BUTTONCOMET_HOT             183
#define IDB_BUTTONCOMET_UP              184
#define IDB_BUTTONSAVE_DISABLED         185
#define IDB_BUTTONSAVE_DOWN             186
#define IDB_BUTTONSAVE_HOT              187
#define IDB_BUTTONSAVE_UP               188
#define IDB_BUTTONSELECT_DISABLED       189
#define IDB_BUTTONSELECT_DOWN           190
#define IDB_BUTTONSELECT_HOT            191
#define IDB_BUTTONSELECT_UP             192
#define IDB_BUTTONSTAR_DISABLED         193
#define IDB_BUTTONSTAR_DOWN             194
#define IDB_BUTTONSTAR_HOT              195
#define IDD_SAVEEDITCHANGES             197
#define IDD_ASKREGISTERING              198
#define IDR_MENU1                       199
#define IDR_SAVECONTEXT                 199
#define IDD_POSTCALIBRATION             199
#define IDS_COLUMN_PATH                 200
#define IDB_COMETTRAILS                 200
#define IDS_COLUMN_FILE                 201
#define IDB_COMETFREEZE                 201
#define IDS_COLUMN_TYPE                 202
#define IDB_COMETNORMAL                 202
#define IDS_COLUMN_SCORE                203
#define IDD_BATCHSTACKING               203
#define IDS_COLUMN_DX                   204
#define IDR_MENU2                       204
#define IDR_COSMETICMETHOD              204
#define IDS_COLUMN_DY                   205
#define IDR_MENU3                       205
#define IDR_FILELISTS                   205
#define IDS_COLUMN_ANGLE                206
#define IDS_COLUMN_DATETIME             207
#define IDD_DIALOG1                     207
#define IDD_ADIALOG                     207
#define IDS_COLUMN_SIZES                208
#define IDD_BACKGROUNDOPTIONS           208
#define IDS_COLUMN_CFA                  209
#define IDR_CALIBRATION                 209
#define IDS_COLUMN_DEPTH                210
#define IDD_RECOMMENDEDSETTINGS         210
#define IDS_COLUMN_INFOS                211
#define IDD_POSTCALIBRATION1            211
#define IDD_OUTPUT                      211
#define IDS_COLUMN_ISO_GAIN             212
#define IDR_SAVESETTINGS                212
#define IDS_COLUMN_EXPOSURE             213
#define IDR_LOADSETTINGS                213
#define IDS_COLUMN_STARS                214
#define IDR_EDITSETTINGS                214
#define IDS_COLUMN_SKYBACKGROUND        215
#define IDS_COLUMN_APERTURE				216
#define IDS_COLUMN_FILTER				217
#define IDS_TYPE_LIGHT                  300
#define IDS_TYPE_DARK                   301
#define IDS_TYPE_FLAT                   302
#define IDS_TYPE_OFFSET                 303
#define IDS_TYPE_MASTERDARK             304
#define IDS_TYPE_MASTEROFFSET           305
#define IDS_TYPE_MASTERFLAT             306
#define IDS_TYPE_DARKFLAT               307
#define IDS_TYPE_MASTERDARKFLAT         308
#define IDS_FORMAT_RGB                  400
#define IDS_FORMAT_GRAY                 401
#define IDS_YES                         402
#define IDS_NO                          403
#define IDS_EXPOSUREFORMAT_SUP          404
#define IDS_EXPOSUREFORMAT_INF          405
#define IDS_OR                          406
#define IDS_AND                         407
#define IDS_ISO                         408
#define IDS_GAIN                        409
#define IDS_EXPOSURE0                   500
#define IDS_EXPOSURE1                   501
#define IDS_EXPOSURE2                   502
#define IDS_EXPOSURE3                   503
#define IDS_NRFRAMES                    504
#define IDS_NOINFO                      505
#define IDS_ESTIMATED0                  506
#define IDS_ESTIMATED1                  507
#define IDS_ESTIMATED2                  508
#define IDS_ESTIMATED3                  509
#define IDS_ESTIMATEDUNKNOWN            510
#define IDS_EXPOSURETIME1               512
#define IDS_EXPOSURETIME2               513
#define IDS_EXPOSURETIME3               514
#define IDS_NRPROCESSORS                515
#define IDS_FILTER_DSIIMAGETIFF         600
#define IDS_FILTER_INPUT                601
#define IDS_FILTER_OUTPUT               602
#define IDS_LISTFILTER_OUTPUT           603
#define IDS_FILTER_MASK                 604
#define IDS_TITLE_MASK                  605
#define IDS_TITLE_OPENLIGHTFRAMES       606
#define IDS_TITLE_OPENDARKFRAMES        607
#define IDS_TITLE_OPENFLATFRAMES        608
#define IDS_TITLE_OPENBIASFRAMES        609
#define IDS_TITLE_OPENDARKFLATFRAMES    610
#define IDS_FILTER_SETTINGFILE          611
#define IDS_TITLE_LOADSETTINGS          612
#define IDS_TITLE_SAVESETTINGS          613
#define IDS_MSG_SAVEMODIFICATIONS       700
#define IDS_MSG_NOPICTURETOSAVE         701
#define IDS_MSG_NOPICTUREFORSTARMASK    702
#define IDS_CHECK_ALLOK                 800
#define IDS_CHECK_DARKFLATOFFSET        801
#define IDS_CHECK_DARKFLAT              802
#define IDS_CHECK_DARKOFFSET            803
#define IDS_CHECK_FLATOFFSET            804
#define IDS_CHECK_DARK                  805
#define IDS_CHECK_FLAT                  806
#define IDS_CHECK_OFFSET                807
#define IDS_TT_REDADJUST                900
#define IDS_TT_GREENADJUST              901
#define IDS_TT_BLUEADJUST               902
#define IDS_TT_APPLIED                  903
#define IDS_TT_EMBEDDED                 904
#define IDS_ASK_DELETESETTINGS          1000
#define IDS_ASK_NODARK                  1001
#define IDS_ASK_NOFLAT                  1002
#define IDS_ASK_NOOFFSET                1003
#define IDS_ASK_CONTINUE                1004
#define IDC_PROCESS                     1015
#define IDC_RESET                       1020
#define IDC_REDGRADIENT                 1024
#define IDC_GREENGRADIENT               1025
#define IDC_BLUEGRADIENT                1026
#define IDC_DARKANGLE                   1029
#define IDC_DARKPOWER                   1030
#define IDC_MIDTONE                     1031
#define IDC_MIDANGLE                    1032
#define IDC_HIGHANGLE                   1033
#define IDC_HIGHPOWER                   1034
#define IDC_SETTINGS                    1035
#define IDC_LINK                        1036
#define IDC_UNDO                        1037
#define IDC_REDO                        1038
#define IDC_SETTINGSNAME                1043
#define IDC_SETTINGSLIST                1044
#define IDC_SATURATION                  1049
#define IDC_RED_HAT                     1050
#define IDC_GREEN_HAT                   1051
#define IDC_FORCEREGISTER               1051
#define IDC_BLUE_HAT                    1052
#define IDC_ISOSPEED                    1054
#define IDC_INFO                        1055
#define IDC_THRESHOLD                   1056
#define IDC_STACK                       1057
#define IDC_PERCENT                     1058
#define IDC_NOWB                        1061
#define IDC_CAMERAWB                    1062
#define IDC_BILINEAR                    1064
#define IDC_VNG                         1065
#define IDC_BISQUARED                   1065
#define IDC_AHD                         1066
#define IDC_BICUBIC                     1066
#define IDC_RGB4COLORS                  1067
#define IDC_BRIGHTNESS                  1070
#define IDC_REDSCALE                    1071
#define IDC_RAWDDPSETTINGS              1071
#define IDC_BLUESCALE                   1072
#define IDC_ST_SATURATION               1072
#define IDC_ST_DARKNESS                 1073
#define IDC_ST_MIDTONE                  1074
#define IDC_ST_HIGHLIGHT                1075
#define IDC_TEXT_DARKNESS               1076
#define IDC_TEXT_MIDTONE                1077
#define IDC_TEXT_HIGHLIGHT              1078
#define IDC_SUPERPIXELS                 1079
#define IDC_RAWBAYER                    1080
#define IDC_PROCESSING_RECT             1084
#define IDC_STACKING_RECT               1085
#define IDC_STACKING_SUBRECT1           1086
#define IDC_STACKING_SUBRECT2           1087
#define IDC_STACKING_SUBRECT3           1088
#define IDC_REGISTERING_REGISTERCHECKED 1090
#define IDC_STACKING_TITLE              1092
#define IDC_PROCESSING_TITLE            1093
#define IDC_STACKING_OPENFILES          1094
#define IDC_STACKING_OPENDARKS          1095
#define IDC_STACKING_CLEARLIST          1096
#define IDC_STACKING_CHECKALL           1097
#define IDC_STACKING_CHECKABOVE         1098
#define IDC_STACKING_UNCHECKALL         1099
#define IDC_STACKING_STACKCHECKED       1100
#define IDS_CREATEMASTERDARK            1100
#define IDC_PROCESSING_OPENFILE         1101
#define IDS_CREATEMASTEROFFSET          1101
#define IDC_PROCESSING_COPYTOCLIPBOARD  1102
#define IDS_ADDOFFSET                   1102
#define IDC_PROCESSING_SAVEFILE         1103
#define IDS_ADDDARK                     1103
#define IDC_OPTIONS_RECT                1104
#define IDS_SAVINGMASTEROFFSET          1104
#define IDC_OPTIONS_TITLE               1105
#define IDS_SAVINGMASTERDARK            1105
#define IDC_OPTIONS_RAWDDPSETTINGS      1106
#define IDS_CREATEMASTERFLAT            1106
#define IDC_STACKING_COMPUTEOFFSETS     1107
#define IDS_ADDFLAT                     1107
#define IDC_APPLIED                     1108
#define IDC_STACKING_OPENFLATS          1108
#define IDS_SAVINGMASTERFLAT            1108
#define IDC_EMBEDDED                    1109
#define IDC_STACKING_OPENOFFSETS        1109
#define IDS_CREATEMASTERDARKFLAT        1109
#define IDC_USERECT                     1110
#define IDC_STACKING_LOADLIST           1110
#define IDS_ADDDARKFLAT                 1110
#define IDC_STACKING_SAVELIST           1111
#define IDS_SAVINGMASTERDARKFLAT        1111
#define IDC_PROCESSING_CREATESTARMASK   1112
#define IDC_SHOWSTARS                   1113
#define IDC_STACKING_BATCHSTACK         1113
#define IDC_STACKWARNING                1114
#define IDC_ABOUT                       1114
#define IDC_LINK_DEEPSKYSTACKER         1115
#define IDC_STACKING_OPENDARKFLATS      1115
#define IDC_LINK_DCRAW                  1116
#define IDC_OPTIONS_SETTINGS            1116
#define IDC_LINK_LIBTIFF                1117
#define IDC_OPTIONS_LOADSETTINGS        1117
#define IDC_VERSION_DEEPSKYSTACKER      1118
#define IDC_OPTIONS_SAVESETTINGS        1118
#define IDC_VERSION_DCRAW               1119
#define IDC_OPTIONS_RECOMMANDEDSETTINGS 1119
#define IDS_REGISTERING                 1120
#define IDC_VERSION_LIBTIFF             1120
#define IDS_REGISTERINGPICTURE          1121
#define IDC_CHECKVERSION                1121
#define IDS_REGISTERINGNAME             1122
#define IDS_REGISTERINGNAMEPLUSTARS     1123
#define IDS_REGISTERINGNAMEPLUSSTARS    1123
#define IDS_COMPUTINGLUMINANCE          1124
#define IDC_RECAP                       1124
#define IDC_VERSION_CFITSIO             1124
#define IDS_LOADRGBPICTURE              1125
#define IDC_LINK_CFITSIO                1125
#define IDS_LOADGRAYPICTURE             1126
#define IDC_EXPOSURE                    1126
#define IDS_LOADRGBDARK                 1127
#define IDC_FILENAME                    1127
#define IDS_LOADGRAYDARK                1128
#define IDC_DATETIME                    1128
#define IDS_ADDRGBDARK                  1129
#define IDC_SIZES                       1129
#define IDS_ADDGRAYDARK                 1130
#define IDC_DEPTH                       1130
#define IDS_LOADRGBOFFSET               1131
#define IDC_TYPE                        1131
#define IDS_LOADGRAYOFFSET              1132
#define IDC_CFA                         1132
#define IDS_ADDRGBOFFSET                1133
#define IDS_ADDGRAYOFFSET               1134
#define IDS_COMPUTINGOFFSETS            1135
#define IDC_AVERAGE                     1135
#define IDS_COMPUTINGSTACKINGINFO       1136
#define IDC_MEDIAN                      1136
#define IDS_STACKING_COMPUTINGOFFSET    1137
#define IDS_STACKING                    1138
#define IDC_SIGMACLIPPING               1138
#define IDS_STACKING_PICTURE            1139
#define IDC_KAPPA                       1139
#define IDS_LOADRGBLIGHT                1140
#define IDC_ITERATION                   1140
#define IDS_LOADGRAYLIGHT               1141
#define IDC_MAXIMUM                     1141
#define IDS_STACKRGBLIGHT               1142
#define IDC_TABRECT                     1142
#define IDC_MEDIANSIGMACLIPPING         1142
#define IDS_STACKGRAYLIGHT              1143
#define IDC_STACKINGPARAMETERS          1143
#define IDS_STACKING_COMPUTINGADJUSTMENT 1144
#define IDS_COMPUTINGADJUSTMENT         1145
#define IDC_CHANGETEMPFOLDER            1145
#define IDS_STACKING_APPLYINGADJUSTMENT 1146
#define IDC_TEMPFOLDER                  1146
#define IDS_STACKING_COMPUTEMAXADJUSTMENT 1147
#define IDS_STACKING_APPLYADJUSTMENT    1148
#define IDC_ENTROPYAVERAGE              1148
#define IDS_COMPUTINGMEDIANOFFSET       1149
#define IDC_AUTOADAPTIVEAVERAGE         1149
#define IDS_COMPUTINGMEDIANDARK         1150
#define IDC_STATICITERATION             1150
#define IDS_COMPUTINGMEDIANFLAT         1151
#define IDC_STATICKAPPA                 1151
#define IDS_LOADRGBFLAT                 1152
#define IDS_LOADGRAYFLAT                1153
#define IDC_KAPPAFRAME                  1153
#define IDC_AUTOADAPTIVEFRAME           1154
#define IDS_ADDRGBFLAT                  1154
#define IDS_ADDGRAYFLAT                 1155
#define IDC_BACKGROUNDCALIBRATION       1155
#define IDS_MEDIANDARKINFO              1156
#define IDC_DARKOPTIMIZATION            1156
#define IDC_COMPRESSION_NONE            1156
#define IDS_MEDIANOFFSETINFO            1157
#define IDC_COMPRESSION_ZIP             1157
#define IDC_PERCHANNELBACKGROUNDCALIBRATION 1157
#define IDS_MEDIANFLATINFO              1158
#define IDC_COMPRESSION_LZW             1158
#define IDC_BACKGROUNDCALIBRATION3      1158
#define IDC_USEDARKFACTOR               1158
#define IDS_SUBSTRACTINGOFFSET          1159
#define IDC_NORMALRESULT                1159
#define IDS_SUBSTRACTINGDARK            1160
#define IDC_MOSAICRESULT                1160
#define IDS_APPLYINGFLAT                1161
#define IDC_MODEPREVIEW                 1161
#define IDS_NORMALIZINGMASTERFLAT       1162
#define IDC_INTERSECTIONMODE            1162
#define IDS_COMPUTINGMINLUMINANCE       1163
#define IDC_HOTPIXELS                   1163
#define IDS_COMPUTINGENTROPY            1164
#define IDS_COMPUTINGBACKGROUNDCALIBRATION 1165
#define IDC_LUMINANCETHRESHOLD          1165
#define IDS_COMPUTINGDARKOPTIMIZATIONFACTOR 1166
#define IDC_COMPUTEDETECTEDSTARS        1166
#define IDS_REMOVINGHOTPIXELS           1167
#define IDC_NRSTARS                     1167
#define IDC_LUMINANCETHRESHOLDTEXT      1168
#define IDS_DETECTINGHOTPIXELS1         1168
#define IDC_SHEETRECT                   1169
#define IDS_DETECTINGHOTPIXELS2         1169
#define IDC_FITSISRAW                   1170
#define IDS_COMPUTINGFLATCALIBRATION    1170
#define IDS_APPLYINGFLATCALIBRATION     1171
#define IDS_AHDDEMOSAICING              1172
#define IDS_PROCESSINGIMAGE             1173
#define IDS_CREATINGSTARMASK            1174
#define IDS_SAVINGSTARMASK              1175
#define IDC_DSLR                        1176
#define IDS_APPLYINGCOSMETIC_HOT        1176
#define IDC_BAYERPATTERN                1177
#define IDS_APPLYINGCOSMETIC_COLD       1177
#define IDS_CREATINGMEDIANIMAGE         1178
#define IDC_APPLY                       1179
#define IDS_OPTIMIZINGDARKMATCHING      1179
#define IDS_LOADRGBDARKFLAT             1180
#define IDC_CREATEINTERMEDIATE          1181
#define IDS_LOADGRAYDARKFLAT            1181
#define IDC_AUTO                        1182
#define IDC_SAVECALIBRATED              1182
#define IDS_COMPUTINGMEDIANDARKFLAT     1182
#define IDC_ALIGNMENTTEXT               1183
#define IDS_MEDIANDARKFLATINFO          1183
#define IDS_COSMETICSTATS               1184
#define IDC_TEXT1                       1185
#define IDS_COMPUTINGCOSMETICSTATS      1185
#define IDC_TEXT2                       1186
#define IDS_LIGHTFRAMEINFO              1186
#define IDC_TEXT3                       1187
#define IDS_LIGHTFRAMEINFOCOMET         1187
#define IDC_TEXT4                       1188
#define IDS_ALIGNINGCHANNEL             1188
#define IDC_TEXT5                       1189
#define IDC_TEXT6                       1190
#define IDC_TEXT7                       1191
#define IDC_TEXT8                       1192
#define IDC_USEALLPROCESSORS            1193
#define IDC_BLACKPOINTTO0               1198
#define IDC_DROPFILESTEXT               1199
#define IDS_LOADDSIMAGE                 1200
#define IDC_LIGHTFRAMES                 1200
#define IDS_LOADPICTURE                 1201
#define IDC_DARKFRAMES                  1201
#define IDS_SAVEDSIMAGE                 1202
#define IDC_FLATFRAMES                  1202
#define IDC_CONTEXTHELP                 1202
#define IDS_SAVINGDSIMAGE               1203
#define IDC_BIASFRAMES                  1203
#define IDC_SAVEASTIFF                  1203
#define IDS_SAVINGTIFF                  1204
#define IDC_SAVEASTIFF2                 1204
#define IDC_SAVEASFITS                  1204
#define IDC_DARKFLATFRAMES              1204
#define IDS_SAVINGPICTURE               1205
#define IDC_SAVEASEXPLANATION           1205
#define IDS_SAVEWITHSETTINGSAPPLIED     1206
#define IDC_REDUCEWORKERTHREADS         1206
#define IDS_SAVEWITHSETTINGSEMBEDDED    1207
#define IDS_LOADRGBTIFF                 1208
#define IDC_ENABLE3XDRIZZLE             1208
#define IDC_STARTHRESHOLD               1208
#define IDS_LOADGRAYTIFF                1209
#define IDC_ENABLE2XDRIZZLE             1209
#define IDC_MINSIZE                     1209
#define IDS_DEEPSKYSTACKER              1210
#define IDC_CUSTOMRECTANGLE             1210
#define IDC_MAXSIZE                     1210
#define IDS_SAVINGINTERMEDIATE          1211
#define IDS_SAVINGFINAL                 1212
#define IDC_PIXELS                      1212
#define IDS_SAVINGCALIBRATED            1213
#define IDC_STARTHRESHOLDTEXT           1213
#define IDS_SAVENOADJUSTMENT            1214
#define IDC_MINSIZETEXT                 1214
#define IDS_LOADRGBFITS                 1215
#define IDC_MAXSIZETEXT                 1215
#define IDS_LOADGRAYFITS                1216
#define IDC_PERCENTTEXT                 1216
#define IDS_SAVINGFITS                  1217
#define IDC_PIXELSTEXT                  1217
#define IDC_STARSHAPEPREVIEW            1218
#define IDS_STARMASKDESCRIPTION         1218
#define IDC_STARSHAPE                   1220
#define IDC_BADCOLUMNREMOVAL            1221
#define IDC_STANDARDSTACKING            1222
#define IDC_COMETSTACKING               1223
#define IDC_ADVANCEDSTACKING            1224
#define IDC_SAVEWITHOUTASKING           1224
#define IDC_DONTSAVEWITHOUTASKING       1225
#define IDC_ASKAGAIN                    1226
#define IDC_DONTSAVE                    1227
#define IDC_REGISTERONE                 1228
#define IDC_REGISTERALL                 1229
#define IDC_RADIO3                      1230
#define IDC_CONTINUE                    1230
#define IDC_NONE                        1230
#define IDC_DETECTCLEANHOT              1231
#define IDC_MINIMUM                     1231
#define IDC_DETECTCLEANCOLD             1232
#define IDC_MIDDLE                      1232
#define IDC_COLDFILTER                  1233
#define IDC_COLDDETECTION               1234
#define IDC_HOTFILTER                   1235
#define IDC_HOTDETECTION                1236
#define IDC_COLDFILTERSTATIC            1237
#define IDC_COLDDETECTIONSTATIC         1238
#define IDC_HOTFILTERSTATIC             1239
#define IDC_HOTDETECTIONSTATIC          1240
#define IDC_SAVEDELTAIMAGE              1241
#define IDC_COMETSAMPLE                 1242
#define IDC_ADDLISTS                    1245
#define IDC_FILELISTS                   1246
#define IDC_CLEARLIST                   1247
#define IDC_WEAK1                       1248
#define IDC_WEAK2                       1249
#define IDC_STRONG1                     1250
#define IDC_STRONG2                     1251
#define IDC_TESTCOSMETIC                1252
#define IDC_REPLACETEXT                 1253
#define IDC_REPLACEMETHOD               1254
#define IDC_ESPACIOPROFUNDO             1255
#define IDC_LUKAVSKY                    1256
#define IDC_LANGUAGE                    1257
#define IDC_FABIOPAPA                   1258
#define IDC_DARKMULTIPLICATIONFACTOR    1259
#define IDC_FRANCESCPRUNEDA             1259
#define IDC_ALIGNCHANNELS               1260
#define IDC_CHECK1                      1261
#define IDC_DEBLOOM                     1261
#define IDC_FORCEUNSIGNED               1261
#define IDC_MEDIANFILTER                1261
#define IDC_SHOWALL                     1261
#define IDC_SAVEDEBAYERED               1261
#define IDC_CREATEOUTPUT                1261
#define IDC_LINEAR                      1262
#define IDC_RATIONAL                    1263
#define IDC_CALIBRATIONPREVIEW          1264
#define IDC_RGBCALIBRATIONPREVIEW       1265
#define IDC_RECOMMANDEDSETTINGS         1265
#define IDC_RECOMMANDEDSETTINGSHTML     1267
#define IDC_CREDITS                     1268
#define IDC_LANGCREDITS                 1269
#define IDC_RECAPHTML                   1269
#define IDC_DEBLOOMSETTINGS             1271
#define IDC_CHECK2                      1273
#define IDC_CREATEHTML                  1273
#define IDC_RADIO1                      1274
#define IDC_USEREFERENCEFRAMEFOLDER     1274
#define IDC_NOALIGNMENT                 1274
#define IDC_RADIO2                      1275
#define IDC_USEANOTHERFOLDER            1275
#define IDC_RADIO4                      1276
#define IDC_AUTOSAVE                    1276
#define IDC_RADIO5                      1277
#define IDC_FILELIST                    1277
#define IDC_CHECK3                      1278
#define IDC_APPENDNUMBER                1278
#define IDC_USEFILELISTFOLDER           1279
#define IDC_OUTPUTFOLDER                1280
#define IDC_INTERSECTIONMODE_TEXT       1281
#define IDC_MODE_TEXT                   1281
#define IDS_COMPUTINGMEDIANLIGHT        1300
#define IDS_LISTINFO                    1400
#define IDS_LISTINFO2                   1401
#define IDS_MAINGROUP                   1500
#define IDS_GROUPIDMASK                 1501
#define IDS_ABOUT_DSS                   1600
#define IDS_ABOUT_DSS_LINK              1601
#define IDS_ABOUT_DCRAW                 1602
#define IDS_ABOUT_DCRAW_LINK            1603
#define IDS_ABOUT_TIFF                  1604
#define IDS_ABOUT_TIFF_LINK             1605
#define IDS_ABOUT_FITS                  1606
#define IDS_ABOUT_FITS_LINK             1607
#define IDS_ABOUT_QHTM                  1608
#define IDS_ABOUT_QHTM_LINK             1609
#define IDS_ABOUT_LANG_SPANISH          1650
#define IDS_ABOUT_LANG_SPANISH_LINK     1651
#define IDS_ABOUT_LANG_CZECH            1652
#define IDS_ABOUT_LANG_CZECH_LINK       1653
#define IDS_ABOUT_LANG_ITALIAN          1654
#define IDS_ABOUT_LANG_ITALIAN_LINK     1655
#define IDS_ABOUT_LANG_CATALAN          1656
#define IDS_ABOUT_LANG_CATALAN_LINK     1657
#define IDS_ABOUT_LANG_GERMAN           1658
#define IDS_ABOUT_LANG_GERMAN_LINK      1659
#define IDS_ABOUT_LANG_DUTCH            1660
#define IDS_ABOUT_LANG_DUTCH_LINK1      1661
#define IDS_ABOUT_LANG_DUTCH_LINK2      1662
#define IDS_ABOUT_LANG_CHINESET         1663
#define IDS_ABOUT_LANG_CHINESET_LINK1   1664
#define IDS_ABOUT_LANG_CHINESET_LINK    1664
#define IDS_ABOUT_LANG_PORTUGUESE       1665
#define IDS_ABOUT_LANG_PORTUGUESE_LINK  1666
#define IDS_ABOUT_LANG_ROMANIAN         1667
#define IDS_ABOUT_LANG_ROMANIAN_LINK    1668
#define IDS_ABOUT_LANG_RUSSIAN          1669
#define IDS_ABOUT_LANG_RUSSIAN_LINK     1670
#define IDS_ABOUT_LANG_TURKISH          1671
#define IDS_ABOUT_LANG_TURKISH_LINK     1672
#define IDS_ERROR_NOTCOMPATIBLE         2000
#define IDS_ERROR_NOTLIGHTCHECKED       2001
#define IDS_ERROR_NOTLIGHTCHECKED2      2002
#define IDS_ERROR_NOTENOUGHFREESPACE    2003
#define IDS_ERROR_CANT_WRITE_DIRECTORY  2004
#define IDS_HAT_LINEAR                  2100
#define IDS_HAT_CUBEROOT                2101
#define IDS_HAT_SQUAREROOT              2102
#define IDS_HAT_LOG                     2103
#define IDS_HAT_LOGLOG                  2104
#define IDS_HAT_LOGSQUAREROOT           2105
#define IDS_HAT_ASINH                   2106
#define IDS_ALIGNMENT_AUTO              2200
#define IDS_ALIGNMENT_BILINEAR          2201
#define IDS_ALIGNMENT_BISQUARED         2202
#define IDS_ALIGNMENT_BICUBIC           2203
#define IDS_ALIGN_AUTO                  2210
#define IDS_ALIGN_BILINEAR              2211
#define IDS_ALIGN_BISQUARED             2212
#define IDS_ALIGN_BICUBIC               2213
#define IDS_ALIGN_NONE                  2214
#define IDS_STACKINGMODE_NORMAL         2300
#define IDS_STACKINGMODE_MOSAIC         2301
#define IDS_STACKINGMODE_INTERSECTION   2302
#define IDS_CHECKVERSION                3000
#define IDS_VERSIONAVAILABLE            3001
#define IDS_TEMPFILEREMOVAL             3002
#define IDS_WARNING_ERASEFILES          3003
#define IDS_WANTTOCONTINUE              3004
#define IDS_WARNINGREADONLY             3005
#define IDS_WARNING_SAVECHANGES         3006
#define IDS_WARNING_ONLYONEFRAME        3007
#define IDS_RECAP_STEP                  4000
#define IDS_RECAP_OFFSET                4001
#define IDS_RECAP_ISOWARNING            4002
#define IDS_RECAP_NOOFFSET              4003
#define IDS_RECAP_DARK                  4004
#define IDS_RECAP_EXPOSUREWARNING       4005
#define IDS_RECAP_NODARK                4006
#define IDS_RECAP_FLAT                  4007
#define IDS_RECAP_NOFLAT                4008
#define IDS_RECAP_TOTALEXPOSURETIME     4009
#define IDS_RECAP_WARNINGBAYERDRIZZLE   4010
#define IDS_RECAP_BACKGROUNDCALIBRATION 4011
#define IDS_RECAP_DARKOPTIMIZATION      4012
#define IDS_RECAP_DARKFLAT              4013
#define IDS_RECAP_ISOWARNINGDARKFLAT    4014
#define IDS_RECAP_EXPOSUREWARNINGDARKFLAT 4015
#define IDS_RECAP_PERCHANNELBACKGROUNDCALIBRATION 4016
#define IDS_RECAP_DARKMULTIPLICATIONFACTOR 4017
#define IDS_RECAP_GAINWARNING           4018
#define IDS_RECAP_GAINWARNINGDARKFLAT   4019
#define IDS_RECAP_METHOD                4049
#define IDS_RECAP_AVERAGE               4050
#define IDS_RECAP_MEDIAN                4051
#define IDS_RECAP_MAXIMUM               4052
#define IDS_RECAP_KAPPASIGMA            4053
#define IDS_RECAP_AUTOADAPTIVE          4054
#define IDS_RECAP_ENTROPYAVERAGE        4055
#define IDS_RECAP_MEDIANSIGMACLIP       4056
#define IDS_RECAP_ALIGNMENT             4057
#define IDS_MULTIPLEFILESELECTED        4100
#define IDS_RECAP_MEGABYTES             4200
#define IDS_RECAP_KILOBYTES             4201
#define IDS_RECAP_GIGABYTES             4202
#define IDS_RECAP_WARNINGDISKSPACE      4250
#define IDS_RECAP_INFODISKSPACE         4251
#define IDS_RECAP_SELECTTEMPFOLDER      4252
#define IDS_RECAP_MOSAIC                4253
#define IDS_RECAP_MOSAICWARNING         4254
#define IDS_RECAP_WARNINGINTERMEDIATESAVE 4255
#define IDS_RECAP_HOTPIXELS             4256
#define IDS_RECAP_DETECTEDANDUSEDPROCESSORS 4257
#define IDS_RECAP_DETECTEDNOTUSEDPROCESSORS 4258
#define IDS_RECAP_DRIZZLE               4259
#define IDS_RECAP_WARNINGDRIZZLE        4260
#define IDS_RECAP_WARNINGJPEG           4261
#define IDS_RECAP_STACKINGMODE          4262
#define IDS_RECAP_STACKINGMODE_NORMAL   4263
#define IDS_RECAP_STACKINGMODE_MOSAIC   4264
#define IDS_RECAP_STACKINGMODE_CUSTOM   4265
#define IDS_RECAP_COMETSTACKING         4266
#define IDS_RECAP_COMETSTACKING_NONE    4267
#define IDS_RECAP_COMETSTACKING_COMET   4268
#define IDS_RECAP_COMETSTACKING_BOTH    4269
#define IDS_RECAP_COSMETICHOT           4270
#define IDS_RECAP_COSMETICCOLD          4271
#define IDS_SELECTOUTPUTFOLDER          4272
#define IDS_RECAP_STACKINGMODE_INTERSECTION 4273
#define IDS_RECO_DISCLAIMER             4496
#define IDS_RECO_CLICKTOSET             4497
#define IDS_RECO_ALREADYSET             4498
#define IDS_RECO_PREREQUISITES          4499
#define IDS_RECO_RAWNARROWBAND_TEXT     4500
#define IDS_RECO_RAWNARROWBAND_REASON   4501
#define IDS_RECO_RAWHIGHSNR_TEXT        4502
#define IDS_RECO_RAWHIGHSNR_REASON      4503
#define IDS_RECO_RAWLOWSNR_TEXT         4504
#define IDS_RECO_RAWLOWSNR_REASON       4505
#define IDS_RECO_RAWSETBP_TEXT          4506
#define IDS_RECO_RAWSETBP_REASON        4507
#define IDS_RECO_RAWCLEARBP_TEXT        4508
#define IDS_RECO_RAWCLEARBP_REASON      4509
#define IDS_RECO_MEDIANFILTER_TEXT      4510
#define IDS_RECO_MEDIANFILTER_REASON    4511
#define IDS_RECO_MODDEDDSLR_TEXT        4512
#define IDS_RECO_MODDEDDSLR_REASON      4513
#define IDS_RECO_USEAVERAGECOMBINE      4514
#define IDS_RECO_COMETSTARTRAILS_REASON 4515
#define IDS_RECO_USESIGMACLIPPING       4516
#define IDS_RECO_COMETSTARSMANY_REASON  4517
#define IDS_RECO_USEMEDIAN              4518
#define IDS_RECO_DARK_REASON            4519
#define IDS_RECO_USESIGMAMEDIAN         4520
#define IDS_RECO_BIAS_REASON            4521
#define IDS_RECO_FLAT_REASON            4522
#define IDS_RECO_PERCHANNELCALIBRATION_REASON 4523
#define IDS_RECO_USEPERCHANNEL          4524
#define IDS_RECO_RGBCALIBRATION_REASON  4525
#define IDS_RECO_USERGBCALIBRATION      4526
#define IDS_RECO_PERCHANNELCALIBRATIONGRAY_REASON 4527
#define IDS_RECO_LIGHT_REASON           4528
#define IDS_RECO_USEAUTOADAPTIVEAVERAGE 4529
#define IDS_GENERIC_RGGB                5000
#define IDS_GENERIC_BGGR                5001
#define IDS_GENERIC_GRBG                5002
#define IDS_GENERIC_GBRG                5003
#define IDS_GENERIC                     5004
#define IDS_TIP_ADDSTAR                 6000
#define IDS_TIP_REMOVESTAR              6001
#define IDS_TIP_SETCOMET                6002
#define IDS_TIP_REMOVECOMET             6003
#define IDS_CAMERA_NOT_SUPPORTED        8001
#define IDS_8BIT_FITS_NODEBAYER			8002
#define IDS_TOOLTIP_KAPPASIGMA          10000
#define IDS_TOOLTIP_AUTOADAPTIVE        10001
#define IDS_TOOLTIP_MEDIANKAPPASIGMA    10002
#define IDS_TOOLTIP_BACKGROUNDCALIBRATION 10003
#define IDS_TOOLTIP_SELECTRECT          10004
#define IDS_TOOLTIP_STAR                10005
#define IDS_TOOLTIP_COMET               10006
#define IDS_TOOLTIP_SAVE                10007
#define IDS_HELPFILE                    20000
#define IDS_FILELISTDESCRIPTION         30000
#define IDM_CHECK                       40002
#define IDM_UNCHECK                     40003
#define IDM_CHANGETOFRAME               40009
#define IDM_CHANGETODARK                40010
#define IDM_CHANGETOFLAT                40011
#define IDM_CHANGETOOFFSET              40012
#define IDM_REMOVEFROMLIST              40013
#define IDM_PROPERTIES                  40017
#define IDM_COPYTOCLIPBOARD             40020
#define IDM_USEASSTARTING               40023
#define IDC_TEXT_SATURATION             40024
#define IDC_TITLE                       40025
#define ID_LISTCONTEXT_SUPPRIMERDUDISQUE 40029
#define IDM_ERASEFROMDISK               40030
#define ID_SAVECONTEXT_SAVEWITHOUTASKING 40031
#define ID_SAVECONTEXT_ASKALWAYS        40033
#define ID_SAVECONTEXT_DONTSAVEWITHOUTASKING 40034
#define ID_LISTCONTEXT_CHANGERENTYPEDARKFLAT 40035
#define ID_CHANGETODARKFLAT             40036
#define IDM_CHANGETODARKFLAT            40037
#define ID_COSMETICMETHOD_MEDIAN        40040
#define ID_COSMETICMETHOD_GAUSSIAN      40041
#define ID_FILELIST_OPENANOTHERFILELIST 40043
#define ID_FILELIST_FIRSTMRU            40044
#define ID_CALIBRATIONMENU_NOBACKGROUNDCALIBRATION 40045
#define ID_CALIBRATIONMENU_PERCHANNELBACKGROUNDCALIBRATION 40046
#define ID_CALIBRATIONMENU_RGBBACKGROUNDCALIBRATION 40047
#define ID_CALIBRATIONMENU_OPTIONS      40048
#define ID_SAVESETTINGS_SAVEASDEEPSKYSTACKERLIVESETTINGS 40050
#define ID_SAVESETTINGS_SAVEAS          40051
#define ID_SAVESETTINGS_FIRSTMRU        40052
#define ID_LOADSETTINGS_LOADDEEPSKYSTACKERLIVESETTINGS 40054
#define ID_LOADSETTINGS_LOAD            40055
#define ID_LOADSETTINGS_RESTOREDEFAULTSETTINGS 40056
#define ID_LOADSETTINGS_FIRSTMRU        40057
#define ID_EDITSETTINGS_REGISTERSETTINGS 40058
#define ID_EDITSETTINGS_STACKINGSETTINGS 40059
#define IDC_STANDARDMODE_TEXT           40060
#define IDC_MOSAICMODE_TEXT             40061

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1282
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
