.\"
.\" Руководство к программе dcraw (Декодер "сырых" (RAW) фотографий)
.\"
.\" (c) Дэвид Коффин, 2006
.\"
.\" Распространяется свободно.
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "21 декабря 2006"
.LO 1
.SH ИМЯ
dcraw - консольный декодер "сырых" (RAW) цифровых фотографий
.SH ОБЗОР
.B dcraw
[\fIОПЦИЯ\fR]... [\fIФАЙЛ\fR]...
.SH ОПИСАНИЕ
.B dcraw
конвертирует "сырые" (RAW) фотографии, показывает 
метаданные и извлекает уменьшенные изображения - миниатюры.
.SH ОПЦИИ
.TP
.B -v
Выдает подробные сообщения - не только предупреждения и ошибки.
.TP
.B -c
Выдает расшифрованное изображение или миниатюру на стандартный
вывод (stdout).
.TP
.B -e
Извлекает сгенерированное фотокамерой изображение-миниатюру,
но не "сырое" изображение. Выдается файл JPEG или PPM, в
зависимости от используемой фотокамеры.
.TP
.B -z
Изменяет время последнего доступа и модификации файлов AVI,
JPEG и файлов "сырого" формата на время получения снимка,
предполагая, что часы фотокамеры настроены на время по Гринвичу.
.TP
.B -i
Идентифицирует файлы без их расшифровки.
На выходе получаем 0 если
.B dcraw
может расшифровать последний файл и 1, если нет.
.B -i -v
показывает метаданные.
.TP
.B ""
.B dcraw
не расшифровывает JPEG файлы!!!
.TP
.B -d
Показывает "сырые" данные как изображение в градациях серого без
интерполяции. Хорош для фотографирования черно-белых документов.
.TP
.B -D
То же, что и
.BR -d ,
но в полностью необработанном виде (без цветового балланса).
.TP
.B -h
Выдает цветное изображение, уменьшенное вдвое. В два раза быстрее,
чем
.BR -q\ 0 .
.TP
.B -q 0
Использует быструю низкокачественную билинейную интерполяцию.
.TP
.B -q 2
Использует интерполяцию VNG (по Переменному Числу Градиентов).
.TP
.B -q 3
Использует интерполяцию AHD (Адаптивную Гомогенно-Ориентированную).
.TP
.B -f
Интерполирует RGB как четыре цвета. Используется, когда на 
полученном изображении видны искажения в виде ложной сетки
2x2 (при VNG интерполяции), или узор в виде "лабиринта" при
AHD интерполяции.
.TP
.B -B сигма_область сигма_диапазон
Использует двустронний фильтр (bilateral filter) для сглаживания
шума с сохранением границ между контрастными областями.
.B сигма_область
измеряется в пикселях, в то время как
.B сигма_диапазон
измеряется в единицах цветового пространства CIELab.
Для начала, попробуйте
.BR -B\ 2\ 4 .
.TP
.B -b яркость
По умолчанию,
.B dcraw
записывает 8-битные PGM/PPM/PAM файлы с гамма кривой BT.709
и уровнем белого в 99%. Использование уровня белого означает,
что шкала яркостей масштабируется таким образом, чтобы 1%
точек исходного RAW-изображения стали белыми. Если результат
получается слишком бледным или слишком темным, опция
.B -b
помогает исправить это. По умолчанию яркость равна 1.0.
.TP
.B -4
Записывает 16-битные линейные псевдо-PGM/PPM/PAM файлы без
применения гамма-коррекции, без уровня белого и без использования
.B -b
.
.TP
.B -T
Выдает на выходе файл формата TIFF (с метаданными) вместо PGM/PPM/PAM.
.TP
.B -k черный
Позволяет указать уровень черного.
Значение по умолчанию зависит от используемой фотокамеры.
.TP
.B -K темновой_кадр.pgm
Вычитает темновой кадр из "сырых" данных. Для получения
темнового кадра сделайте "сырой" снимок в полной темноте
(например, закрыв объектив фотокамеры светонепроницаемой
крышкой) и выполните
.BR dcraw\ -D\ -4\ -j\ -t\ 0 .
.TP
.B -a
Использует автоматический цветовой балланс. По умолчанию 
используется фиксированный цветовой балланс, полученный с
использованием снимка белой карты, сфотографированной при
солнечном свете.
.TP
.B -w
Использует цветовой балланс, заданный фотокамерой.  Если он
не может быть найден, выдается предупреждение и происходит
возврат к значению по умолчанию.
.TP
.B -r множ0 множ1 множ2 множ3
Позволяет установить пользовательский цветовой балланс. 
Используемые множители могут быть взяты из вывода команды
.BR dcraw\ -v .
.TP
.B -H 0
Урезает все пересвеченные области до сплошного белого
(действие по умолчанию).
.TP
.B -H 1
Оставляет пересвеченные области неурезанными в различных
оттенках розового. Позволяет выявить сохранившиеся детали.
.TP
.B -H 2-9
Восстанавливает пересвеченные области. Малые числа больше
подходят для белых областей, большие числа - для цветных.
Попробуйте
.B -H 5
в качестве компромиссного варианта. Если результат
выглядит недостаточно хорошо, выполните
.BR -H\ 9 ,
вырежьте цветные пересвеченные области, и вставьте их в
изображение, сгенерированное командой
.BR -H\ 3 .
.TP
.B -m
То же, что и
.BR -o\ 0 .
.TP
.B -o [0-5]
Позволяет выбрать выходное цветовое пространство, при
использовании опции
.B -p
:

.B 0
\ \ Вывод в собственном цветовом пространстве камеры
(уникально для каждой фотокамеры)
.br
.B 1
\ \ sRGB D65 (по умолчанию)
.br
.B 2
\ \ Adobe RGB (1998) D65
.br
.B 3
\ \ Wide Gamut RGB D65
.br
.B 4
\ \ Kodak ProPhoto RGB D65
.br
.B 5
\ \ XYZ
.TP
.BR -p\ фотокамера.icm \ [\  -o\ вывод.icm \ ]
Использует ICC профили для задания собственного цветового 
пространства фотокамеры и выводимого цветового пространства 
(sRGB по умолчанию).
.TP
.B -p embed
Использует ICC профиль, внедренный в "сырой" снимок.
.TP
.B -t [0-7,90,180,270]
Поворачивает выводимое фото. По умолчанию,
.B dcraw
применяется поворот, заданный фотокамерой.
.B -t 0
отключает все виды вращения.
.TP
.B -s [0-99]
Позволяет выбрать, какое "сырое" изображение расшифровать,
если исходный файл содержит более одного изображения.
Например, фотокамеры Fuji\ Super\ CCD\ SR генерируют второе
изображение, недоэкспонированное на 4 шага диафрагмы, что
позволяет запечатлеть детали в пересвеченных областях.
.TP
.B -j
Для фотокамер Fuji\ Super\ CCD показывает изображение,
повернутое на 45 градусов. Для фотокамер с неквадратными
пикселями выдает изображение нерастянутым, с сохранением его
оригинальных пропорций. В любом случае, каждый выводимый
пиксель соответствует одному "сырому" пикселю.
.TP
.B ""
Если они не подходят для вашей фотокамеры,
.B -s
и
.B -j
игнорируются без выдачи каких-либо сообщений.
.SH ФАЙЛЫ
.TP
\:./.badpixels, ../.badpixels, ../../.badpixels, ...
Список поврежденный пикселов вашей фотокамеры, указывающий
.B dcraw
интерполировать вокруг их. Каждая строка определяет колонку, ряд
и Юниксовое время повреждения одного пикселя. Например:
.sp 1
.nf
 962   91 1028350000  # пиксель поврежден между 1 и 4 августа 2002 года
1285 1067 0           # время повреждения пикселя не известно
.fi
.sp 1
Эти координаты определяются для изображений, к которым не были
применены какие-либо виды вырезания или поворота, поэтому используйте 
.B dcraw -j -t 0
для локализации поврежденных пикселов.
.SH "СМОТРИ ТАКЖЕ"
.BR pgm (5),
.BR ppm (5),
.BR pam (5),
.BR pnmgamma (1),
.BR pnmtotiff (1),
.BR pnmtopng (1),
.BR gphoto2 (1),
.BR cjpeg (1),
.BR djpeg (1)
.SH АВТОР
Дэвид Коффин, dcoffin улитка cybercom точка net
