.\"
.\" Manpaĝo por dcraw
.\"
.\" Kopirajte 2006 de David Coffin
.\"
.\" Por libera distribuo
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "21 decembro 2006"
.LO 1
.SH NOMO
dcraw - komand-linia deĉifrilo por krudaj ciferecaj fotoj
.SH RESUMO
.B dcraw
[\fIOPCIO\fR]... [\fIDOSIERO\fR]...
.SH PRISKRIBO
.B dcraw
deĉifras krudajn fotojn, montras pridatumon, kaj eltiras bildetojn.
.SH OPCIOJ
.TP
.B -v
Donu abundajn mesaĝojn, ne nur avertojn kaj erarojn.
.TP
.B -c
Skribu deĉifritajn bild(et)ojn al la ĉefeligujo (stdout).
.TP
.B -e
Eltiru la bildeton generitan de la fotilo, ne la krudan bildon.
Estos dosiero aŭ JPEG aŭ PPM, depende de la fotilo.
.TP
.B -z
Por dosiero kruda, JPEG, aŭ AVI, ŝanĝu la tempojn de lasta aliro
kaj modifo al la tempo de obturado, supozante ke la fotila horloĝo
tenas Universalan Tempon.
.TP
.B -i
Identigu dosierojn sed ne deĉifru ilin.
Eliru kun 0 se
.B dcraw
povas deĉifri la lastan dosieron, aŭ kun 1 se ĝi ne povas.
.B -i -v
montras pridatumon.
.TP
.B ""
.B dcraw
ne povas deĉifri JPEG-dosierojn!!
.TP
.B -d
Montru la krudan datumon grizskala sen interpolado.
Estas bone por foti nigrablankajn dokumentojn.
.TP
.B -D
Same kiel
.BR -d ,
sed tute krude (sen kolor-multipliko).
.TP
.B -h
Eligu duon-grandan koloran bildon.  Duoble pli rapide ol
.BR -q\ 0 .
.TP
.B -q 0
Interpolu per simpla bilinia averaĝado.
.TP
.B -q 2
Interpolu per Variabla Nombro de Gradientoj (VNG).
.TP
.B -q 3
Interpolu per Adapta Homogena Direkto (AHD).
.TP
.B -f
Interpolu RVB-on kiel kvar kolorojn.  Uzu tion ĉi se la
eligo montras falsan 2-je-2 reton per VNG aŭ labirinton
per AHD.
.TP
.B -B sigma_spaco sigma_koloro
Uzu bilateran filtron por glatigi bruon kaj konservi randojn.
.B sigma_spaco
mezuriĝas en bilderoj;
.B sigma_koloro
mezuriĝas en unuoj de kolorspaco CIELab.
Provu komenci per
.B -B\ 2\ 4
.
.TP
.B -b heleco
.B dcraw
supozas skribi 8-bitan PGM/PPM/PAM kun la gama kurbo BT.709 kaj
blanka punkto ĉe la 99a procento.  Uzu tiun ĉi opcion se la bildo
tro helas aŭ malhelas.  La supoza heleco estas 1.0.
.TP
.B -4
Skribu 16-bitan linian pseŭdo-PGM/PPM/PAM sen gama kurbo,
sen blanka punkto, kaj sen la opcio
.B -b
.
.TP
.B -T
Skribu TIFF-on (kun pridatumo) anstataŭ PGM/PPM/PAM.
.TP
.B -k nigra
Agordu la nigran punkton.  La supozo dependas de la fotilo.
.TP
.B -K senlumo.pgm
Subtrahu senluman bildon de la kruda datumo.  Por generi tian
bildon, faru jene al senluma kruda foto:
.BR dcraw\ -D\ -4\ -j\ -t\ 0 .
.TP
.B -a
Aŭtomata kolor-multipliko.  La supozo estas fiksa multipliko
bazita de blanka karto fotita en suno.
.TP
.B -w
Uzu la kolor-multiplikon specifitan de la fotilo.  Se tio ne
troveblas, avertu kaj refalu al la supozo.
.TP
.B -r mul0 mul1 mul2 mul3
Specifu proprajn kolor-multiplikantojn.  Eblas kopii ilin de
la mesaĝoj el 
.BR dcraw\ -v .
.TP
.B -H 0
Blankigu ĉiujn brilaĵojn (la supozo).
.TP
.B -H 1
Lasu brilaĵojn fuksinaj por malkaŝi detalojn.
.TP
.B -H 2-9
Rekonstruu brilaĵojn.  Malaltaj numeraloj favoras blankecon;
altaj numeraloj favoras kolorojn.  Provu
.B -H 5
kiel kompromison.  Se tio ne sufiĉe bonas, faru
.BR -H\ 9 ,
eltranĉu la neblankajn brilaĵojn, kaj gluu ilin en foton
generitan per
.BR -H\ 3 .
.TP
.B -m
Same kiel
.BR -o\ 0 .
.TP
.B -o [0-5]
Elektu la eligotan kolorspacon kiam vi ne uzas la opcion
.B -p
:
.B \t0
\ \ Kruda koloro (unika por ĉiu fotilo)
.br
.B \t1
\ \ sRGB D65 (la supozo)
.br
.B \t2
\ \ Adobe RGB (1998) D65
.br
.B \t3
\ \ Wide Gamut RGB D65
.br
.B \t4
\ \ Kodak ProPhoto RGB D65
.br
.B \t5
\ \ XYZ
.TP
.BR -p\ fotilo.icm \ [\  -o\ eligo.icm \ ]
Uzu ICC profilojn por difini la krudan kolorspacon de la fotilo
kaj la eligotan kolorspacon (sRGB laŭ supozo).
.TP
.B -p embed
Uzu la ICC-profilon internan de la kruda foto.
.TP
.B -t [0-7,90,180,270]
Turnu la bildon.
.B dcraw
supozas apliki la turnon specifitan de la fotilo.
.B -t 0
preventas ian ajn turnadon.
.TP
.B -s [0-99]
Elektu krudan bildon por deĉifri, se la dosiero enhavas pli ol unu.
Ekzemple fotiloj kun Fuji\ Super\ CCD\ SR generas duan bildon, kvar
paŝojn pli malhelan, por montri detalojn en la brilaĵoj.
.TP
.B -j
Por fotiloj kun Fuji\ Super\ CCD, montru la bildon klinita 45
gradojn.  Por fotiloj kun nekvadrataj bilderoj, ne streĉu la bildon
al ĝia ĝusta proporcio.  Ĉiakaze, tiu ĉi opcio neprigas, ke ĉiu
eligata bildero respondos unu krudan bilderon.
.TP
.B ""
Se ili ne taŭgas vian fotilon,
.B -s
kaj
.B -j
silente ignoriĝas.
.SH DOSIEROJ
.TP
\:./.badpixels, ../.badpixels, ../../.badpixels, ...
Listo de mortintaj bilderoj en via fotilo, por ke
.B dcraw
interpolu ĉirkaŭ ili.  Ĉiu linio specifas la kolumnon, vicon,
kaj Uniksan tempon de morto por unu bildero.  Ekzemple:
.sp 1
.nf
 962   91 1028350000  # mortis inter 1a kaj 4a aŭgusto 2002
1285 1067 0           # ne scias kiam mortis tiu ĉi bildero
.fi
.sp 1
Tiuj ĉi koordinatoj antaŭas ĉian tondadon aŭ rotacion, do uzu
.B dcraw -j -t 0
por lokalizi mortintajn bilderojn.
.SH "VIDU ANKAŬ"
.BR pgm (5),
.BR ppm (5),
.BR pam (5),
.BR pnmgamma (1),
.BR pnmtotiff (1),
.BR pnmtopng (1),
.BR gphoto2 (1),
.BR cjpeg (1),
.BR djpeg (1)
.SH AŬTORO
David Coffin, dcoffin heliko cybercom punkto net
